# Strongly inspired from
# https://github.com/actions/starter-workflows/blob/main/ci/python-package.yml

name: Python pull request validation

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml') }}
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv project
      run: | 
        uv sync --all-extras --dev
    - name: Linter + imports
      run: |
        uv run ruff check bff_simulator tests
    - name: Format
      run: |
        uv run ruff format bff_simulator tests --check
    - name: Type hints
      run: |
        uv run mypy bff_simulator tests
    - name: Test
      run: |
        uv run pytest tests
